version: '3.8'

services:
  backend:
    image: backend:latest
    container_name: trading-backend
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///data/trading.db
      - CORS_ORIGINS=http://localhost,http://127.0.0.1,https://divestifi.com,http://divestifi.com,https://api.divestifi.com,http://api.divestifi.com,https://${DOMAIN_NAME:-divestifi.com},http://${DOMAIN_NAME:-divestifi.com}
      - LOG_LEVEL=INFO
      - INITIAL_BALANCE=100000.0
      - MAX_POSITION_SIZE=0.05
      - ENABLE_SCHEDULER=false
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
      - NEWS_API_KEY=${NEWS_API_KEY:-}
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY:-}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      # Add health check environment
      - HEALTH_CHECK_ENABLED=true
    expose:
      - "8000"
    volumes:
      - backend_data:/app/data
      - backend_logs:/app/logs
    networks:
      - trading_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: frontend:latest
    container_name: trading-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
    expose:
      - "80"
    networks:
      - trading_network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: trading-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - trading_network
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy

  scheduler:
    image: backend:latest
    container_name: trading-scheduler
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///data/trading.db
      - LOG_LEVEL=INFO
      - ENABLE_SCHEDULER=true
      - NEWS_API_KEY=${NEWS_API_KEY:-}
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY:-}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
    volumes:
      - backend_data:/app/data
      - backend_logs:/app/logs
    networks:
      - trading_network
    depends_on:
      backend:
        condition: service_healthy
    command: ["python", "scheduler.py"]

volumes:
  backend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/trading/data
  backend_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/trading/logs

networks:
  trading_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16