version: '3.8'

services:
  backend:
    image: 907391580367.dkr.ecr.us-east-1.amazonaws.com/trading-platform-backend:latest
    container_name: trading-backend
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///data/trading.db
      - CORS_ORIGINS=http://localhost,https://${DOMAIN_NAME:-localhost}
      - LOG_LEVEL=INFO
      - INITIAL_BALANCE=100000.0
      - MAX_POSITION_SIZE=0.05
      - ENABLE_SCHEDULER=true
      - SECRET_KEY=${SECRET_KEY:-change-me-in-production}
      - NEWS_API_KEY=${NEWS_API_KEY:-}
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY:-}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    networks:
      - trading-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: 907391580367.dkr.ecr.us-east-1.amazonaws.com/trading-platform-frontend:latest
    container_name: trading-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_logs:/var/log/nginx
    networks:
      - trading-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  trading-network:
    driver: bridge

volumes:
  trading-data:
    driver: local
  trading-logs:
    driver: local